# Generated by Django 5.2 on 2025-04-18 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_follow_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genres', models.JSONField(default=list)),
                ('favorite_moods', models.JSONField(default=list)),
                ('average_tempo', models.FloatField(blank=True, null=True)),
                ('average_danceability', models.FloatField(blank=True, null=True)),
                ('average_energy', models.FloatField(blank=True, null=True)),
                ('average_valence', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
