# Generated by Django 5.2 on 2025-04-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences_completed',
            field=models.BooleanField(default=False),
        ),
    ]
