# Generated by Django 5.2 on 2025-04-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_preferences_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='portfolio_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
