# Generated by Django 5.2 on 2025-04-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_interaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artwork_url',
        ),
        migrations.RemoveField(
            model_name='track',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='track',
            name='artwork_file',
            field=models.ImageField(blank=True, null=True, upload_to='artwork_files/'),
        ),
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='demo_start_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
