# Generated by Django 5.2 on 2025-04-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_track_artwork_url_remove_track_audio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackfeature',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
