# Generated by Django 5.2 on 2025-04-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_trackfeature_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='anghami_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='spotify_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
